#@load ./extract-all-files.bro
#@load ./extract-common-exploit-types.bro
#@load ./extract-java.bro
#@load ./extract-ms-office.bro
#@load ./extract-pdf.bro
#@load ./extract-pe.bro
#@load ./store-files-by-md5.bro
#@load ./store-files-by-sha1.bro
#@load ./store-files-by-sha256.bro
